# Generated by Django 4.2.7 on 2023-12-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Car Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('mileage', models.IntegerField(verbose_name='Mileage')),
                ('engine_mode', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], max_length=50, verbose_name='Engine Mode')),
                ('price_per_day', models.IntegerField(verbose_name='Price Per Day')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Image')),
            ],
        ),
    ]
