# Generated by Django 4.2.7 on 2023-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargarage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Car Description'),
        ),
    ]
