# Generated by Django 4.2.7 on 2023-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0002_cargarage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargarage',
            name='description',
            field=models.TextField(verbose_name='Car Description'),
        ),
    ]
