# Generated by Django 4.2.7 on 2023-12-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0003_alter_cargarage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargarage',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
