# Generated by Django 4.2.7 on 2023-12-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0004_cargarage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargarage',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
