# Generated by Django 4.2.7 on 2023-12-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0006_rename_mileage_cargarage_fuel_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargarage',
            name='fuel_consumption',
            field=models.IntegerField(verbose_name='Fuel Consumption'),
        ),
    ]
