# Generated by Django 4.2.7 on 2023-12-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0007_alter_cargarage_fuel_consumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads', verbose_name='Image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carhirehome.cargarage')),
            ],
        ),
    ]
