# Generated by Django 4.2.7 on 2023-12-16 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carhirehome', '0008_carimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('special_request', models.TextField()),
                ('payment_method', models.CharField(choices=[('Paypal', 'Payal'), ('Check', 'Check'), ('Transfer', 'Transfer')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarsRented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(default=None)),
                ('car_returned', models.BooleanField(default=False)),
                ('admin_comment', models.TextField()),
                ('CarBooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carhirehome.carbooking')),
            ],
        ),
    ]
